/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#001a42",
        "error-container": "#ffdad6",
        "surface-container-low": "#f2f3f9",
        "on-surface": "#191c20",
        "surface": "#f8f9ff",
        "surface-container": "#eceef3",
        "primary": "#004191",
        "tertiary-container": "#825100",
        "inverse-surface": "#2e3135",
        "primary-fixed": "#d8e2ff",
        "background": "#f8f9ff",
        "surface-container-highest": "#e1e2e8",
        "secondary": "#006c49",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e7e8ee",
        "primary-container": "#0058be",
        "outline": "#727785",
        "secondary-fixed-dim": "#81d8ad",
        "on-tertiary-fixed": "#2a1700",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c2c6d5",
        "on-tertiary-fixed-variant": "#653e00",
        "tertiary": "#623c00",
        "surface-bright": "#f8f9ff",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#002113",
        "secondary-container": "#9af2c5",
        "on-secondary-container": "#0c714d",
        "on-primary-fixed-variant": "#004395",
        "on-surface-variant": "#424753",
        "on-tertiary-container": "#ffcb8f",
        "tertiary-fixed": "#ffddb8",
        "on-secondary-fixed-variant": "#005236",
        "surface-dim": "#cbdbf5",
        "secondary-fixed": "#9df4c8",
        "on-secondary": "#ffffff",
        "on-primary-container": "#c4d5ff",
        "inverse-on-surface": "#eff0f6",
        "surface-tint": "#085ac0",
        "inverse-primary": "#adc6ff",
        "tertiary-fixed-dim": "#fcba66",
        "error": "#ba1a1a",
        "surface-variant": "#e1e2e8",
        "on-background": "#191c20",
        "primary-fixed-dim": "#adc6ff",
        "on-error": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        xxl: "48px",
        "margin-mobile": "24px",
        lg: "24px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        base: "4px",
        gutter: "24px",
        xl: "32px",
        "container-max": "1280px",
      },
      fontFamily: {
        display: ["Quicksand"],
        "body-md": ["Quicksand"],
        "label-sm": ["Plus Jakarta Sans"],
        "headline-md": ["Quicksand"],
        "headline-lg-mobile": ["Quicksand"],
        "body-lg": ["Quicksand"],
        "label-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Quicksand"],
      },
      fontSize: {
        display: ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}
